// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proxy.proto

package proxy_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PUTRenegotiateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SdpAnswer     string                 `protobuf:"bytes,2,opt,name=sdp_answer,json=sdpAnswer,proto3" json:"sdp_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PUTRenegotiateSessionRequest) Reset() {
	*x = PUTRenegotiateSessionRequest{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PUTRenegotiateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PUTRenegotiateSessionRequest) ProtoMessage() {}

func (x *PUTRenegotiateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PUTRenegotiateSessionRequest.ProtoReflect.Descriptor instead.
func (*PUTRenegotiateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *PUTRenegotiateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PUTRenegotiateSessionRequest) GetSdpAnswer() string {
	if x != nil {
		return x.SdpAnswer
	}
	return ""
}

type PUTRenegotiateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PUTRenegotiateSessionResponse) Reset() {
	*x = PUTRenegotiateSessionResponse{}
	mi := &file_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PUTRenegotiateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PUTRenegotiateSessionResponse) ProtoMessage() {}

func (x *PUTRenegotiateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PUTRenegotiateSessionResponse.ProtoReflect.Descriptor instead.
func (*PUTRenegotiateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

type EmitParicipantJoinedToRomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitParicipantJoinedToRomRequest) Reset() {
	*x = EmitParicipantJoinedToRomRequest{}
	mi := &file_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitParicipantJoinedToRomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitParicipantJoinedToRomRequest) ProtoMessage() {}

func (x *EmitParicipantJoinedToRomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitParicipantJoinedToRomRequest.ProtoReflect.Descriptor instead.
func (*EmitParicipantJoinedToRomRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *EmitParicipantJoinedToRomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type EmitParicipantJoinedToRomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitParicipantJoinedToRomResponse) Reset() {
	*x = EmitParicipantJoinedToRomResponse{}
	mi := &file_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitParicipantJoinedToRomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitParicipantJoinedToRomResponse) ProtoMessage() {}

func (x *EmitParicipantJoinedToRomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitParicipantJoinedToRomResponse.ProtoReflect.Descriptor instead.
func (*EmitParicipantJoinedToRomResponse) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{3}
}

var File_proxy_proto protoreflect.FileDescriptor

const file_proxy_proto_rawDesc = "" +
	"\n" +
	"\vproxy.proto\x12\n" +
	"proxy_grpc\"\\\n" +
	"\x1cPUTRenegotiateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"sdp_answer\x18\x02 \x01(\tR\tsdpAnswer\"\x1f\n" +
	"\x1dPUTRenegotiateSessionResponse\";\n" +
	" EmitParicipantJoinedToRomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"#\n" +
	"!EmitParicipantJoinedToRomResponse2\xf6\x01\n" +
	"\fProxyService\x12l\n" +
	"\x15PUTRenegotiateSession\x12(.proxy_grpc.PUTRenegotiateSessionRequest\x1a).proxy_grpc.PUTRenegotiateSessionResponse\x12x\n" +
	"\x19EmitParicipantJoinedToRom\x12,.proxy_grpc.EmitParicipantJoinedToRomRequest\x1a-.proxy_grpc.EmitParicipantJoinedToRomResponseB\x11Z\x0fgrpc/proxy_grpcb\x06proto3"

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_proto_goTypes = []any{
	(*PUTRenegotiateSessionRequest)(nil),      // 0: proxy_grpc.PUTRenegotiateSessionRequest
	(*PUTRenegotiateSessionResponse)(nil),     // 1: proxy_grpc.PUTRenegotiateSessionResponse
	(*EmitParicipantJoinedToRomRequest)(nil),  // 2: proxy_grpc.EmitParicipantJoinedToRomRequest
	(*EmitParicipantJoinedToRomResponse)(nil), // 3: proxy_grpc.EmitParicipantJoinedToRomResponse
}
var file_proxy_proto_depIdxs = []int32{
	0, // 0: proxy_grpc.ProxyService.PUTRenegotiateSession:input_type -> proxy_grpc.PUTRenegotiateSessionRequest
	2, // 1: proxy_grpc.ProxyService.EmitParicipantJoinedToRom:input_type -> proxy_grpc.EmitParicipantJoinedToRomRequest
	1, // 2: proxy_grpc.ProxyService.PUTRenegotiateSession:output_type -> proxy_grpc.PUTRenegotiateSessionResponse
	3, // 3: proxy_grpc.ProxyService.EmitParicipantJoinedToRom:output_type -> proxy_grpc.EmitParicipantJoinedToRomResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
