// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proxy.proto

package proxy_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyService_PUTRenegotiateSession_FullMethodName     = "/proxy_grpc.ProxyService/PUTRenegotiateSession"
	ProxyService_EmitParicipantJoinedToRom_FullMethodName = "/proxy_grpc.ProxyService/EmitParicipantJoinedToRom"
)

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyServiceClient interface {
	PUTRenegotiateSession(ctx context.Context, in *PUTRenegotiateSessionRequest, opts ...grpc.CallOption) (*PUTRenegotiateSessionResponse, error)
	EmitParicipantJoinedToRom(ctx context.Context, in *EmitParicipantJoinedToRomRequest, opts ...grpc.CallOption) (*EmitParicipantJoinedToRomResponse, error)
}

type proxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyServiceClient(cc grpc.ClientConnInterface) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) PUTRenegotiateSession(ctx context.Context, in *PUTRenegotiateSessionRequest, opts ...grpc.CallOption) (*PUTRenegotiateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PUTRenegotiateSessionResponse)
	err := c.cc.Invoke(ctx, ProxyService_PUTRenegotiateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) EmitParicipantJoinedToRom(ctx context.Context, in *EmitParicipantJoinedToRomRequest, opts ...grpc.CallOption) (*EmitParicipantJoinedToRomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitParicipantJoinedToRomResponse)
	err := c.cc.Invoke(ctx, ProxyService_EmitParicipantJoinedToRom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
// All implementations must embed UnimplementedProxyServiceServer
// for forward compatibility.
type ProxyServiceServer interface {
	PUTRenegotiateSession(context.Context, *PUTRenegotiateSessionRequest) (*PUTRenegotiateSessionResponse, error)
	EmitParicipantJoinedToRom(context.Context, *EmitParicipantJoinedToRomRequest) (*EmitParicipantJoinedToRomResponse, error)
	mustEmbedUnimplementedProxyServiceServer()
}

// UnimplementedProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyServiceServer struct{}

func (UnimplementedProxyServiceServer) PUTRenegotiateSession(context.Context, *PUTRenegotiateSessionRequest) (*PUTRenegotiateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PUTRenegotiateSession not implemented")
}
func (UnimplementedProxyServiceServer) EmitParicipantJoinedToRom(context.Context, *EmitParicipantJoinedToRomRequest) (*EmitParicipantJoinedToRomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmitParicipantJoinedToRom not implemented")
}
func (UnimplementedProxyServiceServer) mustEmbedUnimplementedProxyServiceServer() {}
func (UnimplementedProxyServiceServer) testEmbeddedByValue()                      {}

// UnsafeProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServiceServer will
// result in compilation errors.
type UnsafeProxyServiceServer interface {
	mustEmbedUnimplementedProxyServiceServer()
}

func RegisterProxyServiceServer(s grpc.ServiceRegistrar, srv ProxyServiceServer) {
	// If the following call pancis, it indicates UnimplementedProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyService_ServiceDesc, srv)
}

func _ProxyService_PUTRenegotiateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PUTRenegotiateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).PUTRenegotiateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_PUTRenegotiateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).PUTRenegotiateSession(ctx, req.(*PUTRenegotiateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_EmitParicipantJoinedToRom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitParicipantJoinedToRomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).EmitParicipantJoinedToRom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_EmitParicipantJoinedToRom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).EmitParicipantJoinedToRom(ctx, req.(*EmitParicipantJoinedToRomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyService_ServiceDesc is the grpc.ServiceDesc for ProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy_grpc.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PUTRenegotiateSession",
			Handler:    _ProxyService_PUTRenegotiateSession_Handler,
		},
		{
			MethodName: "EmitParicipantJoinedToRom",
			Handler:    _ProxyService_EmitParicipantJoinedToRom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
