// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: ws.proto

package ws_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmitRoomCreatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRoomCreatedRequest) Reset() {
	*x = EmitRoomCreatedRequest{}
	mi := &file_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRoomCreatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRoomCreatedRequest) ProtoMessage() {}

func (x *EmitRoomCreatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRoomCreatedRequest.ProtoReflect.Descriptor instead.
func (*EmitRoomCreatedRequest) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{0}
}

func (x *EmitRoomCreatedRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type EmitRoomCreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRoomCreatedResponse) Reset() {
	*x = EmitRoomCreatedResponse{}
	mi := &file_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRoomCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRoomCreatedResponse) ProtoMessage() {}

func (x *EmitRoomCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRoomCreatedResponse.ProtoReflect.Descriptor instead.
func (*EmitRoomCreatedResponse) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{1}
}

type EmitJoinRoomReequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RoomId             string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ParticipantAddress string                 `protobuf:"bytes,2,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	SessionId          string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SdpAnswer          string                 `protobuf:"bytes,4,opt,name=sdp_answer,json=sdpAnswer,proto3" json:"sdp_answer,omitempty"`
	SdpOffer           string                 `protobuf:"bytes,5,opt,name=sdp_offer,json=sdpOffer,proto3" json:"sdp_offer,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EmitJoinRoomReequest) Reset() {
	*x = EmitJoinRoomReequest{}
	mi := &file_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitJoinRoomReequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitJoinRoomReequest) ProtoMessage() {}

func (x *EmitJoinRoomReequest) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitJoinRoomReequest.ProtoReflect.Descriptor instead.
func (*EmitJoinRoomReequest) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{2}
}

func (x *EmitJoinRoomReequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EmitJoinRoomReequest) GetParticipantAddress() string {
	if x != nil {
		return x.ParticipantAddress
	}
	return ""
}

func (x *EmitJoinRoomReequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EmitJoinRoomReequest) GetSdpAnswer() string {
	if x != nil {
		return x.SdpAnswer
	}
	return ""
}

func (x *EmitJoinRoomReequest) GetSdpOffer() string {
	if x != nil {
		return x.SdpOffer
	}
	return ""
}

type EmitJoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitJoinRoomResponse) Reset() {
	*x = EmitJoinRoomResponse{}
	mi := &file_ws_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitJoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitJoinRoomResponse) ProtoMessage() {}

func (x *EmitJoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitJoinRoomResponse.ProtoReflect.Descriptor instead.
func (*EmitJoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{3}
}

type EmitRequireRenegotiateSessionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RoomId             string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ParticipantAddress string                 `protobuf:"bytes,2,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
	SessionId          string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SdpOffer           string                 `protobuf:"bytes,4,opt,name=sdp_offer,json=sdpOffer,proto3" json:"sdp_offer,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EmitRequireRenegotiateSessionRequest) Reset() {
	*x = EmitRequireRenegotiateSessionRequest{}
	mi := &file_ws_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequireRenegotiateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequireRenegotiateSessionRequest) ProtoMessage() {}

func (x *EmitRequireRenegotiateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequireRenegotiateSessionRequest.ProtoReflect.Descriptor instead.
func (*EmitRequireRenegotiateSessionRequest) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{4}
}

func (x *EmitRequireRenegotiateSessionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EmitRequireRenegotiateSessionRequest) GetParticipantAddress() string {
	if x != nil {
		return x.ParticipantAddress
	}
	return ""
}

func (x *EmitRequireRenegotiateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EmitRequireRenegotiateSessionRequest) GetSdpOffer() string {
	if x != nil {
		return x.SdpOffer
	}
	return ""
}

type EmitRequireRenegotiateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequireRenegotiateSessionResponse) Reset() {
	*x = EmitRequireRenegotiateSessionResponse{}
	mi := &file_ws_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequireRenegotiateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequireRenegotiateSessionResponse) ProtoMessage() {}

func (x *EmitRequireRenegotiateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequireRenegotiateSessionResponse.ProtoReflect.Descriptor instead.
func (*EmitRequireRenegotiateSessionResponse) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{5}
}

var File_ws_proto protoreflect.FileDescriptor

const file_ws_proto_rawDesc = "" +
	"\n" +
	"\bws.proto\x12\x06ws_srv\"1\n" +
	"\x16EmitRoomCreatedRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x19\n" +
	"\x17EmitRoomCreatedResponse\"\xbb\x01\n" +
	"\x14EmitJoinRoomReequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12/\n" +
	"\x13participant_address\x18\x02 \x01(\tR\x12participantAddress\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"sdp_answer\x18\x04 \x01(\tR\tsdpAnswer\x12\x1b\n" +
	"\tsdp_offer\x18\x05 \x01(\tR\bsdpOffer\"\x16\n" +
	"\x14EmitJoinRoomResponse\"\xac\x01\n" +
	"$EmitRequireRenegotiateSessionRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12/\n" +
	"\x13participant_address\x18\x02 \x01(\tR\x12participantAddress\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsdp_offer\x18\x04 \x01(\tR\bsdpOffer\"'\n" +
	"%EmitRequireRenegotiateSessionResponse2\xb1\x02\n" +
	"\x11WebsocketServices\x12R\n" +
	"\x0fEmitRoomCreated\x12\x1e.ws_srv.EmitRoomCreatedRequest\x1a\x1f.ws_srv.EmitRoomCreatedResponse\x12J\n" +
	"\fEmitJoinRoom\x12\x1c.ws_srv.EmitJoinRoomReequest\x1a\x1c.ws_srv.EmitJoinRoomResponse\x12|\n" +
	"\x1dEmitRequireRenegotiateSession\x12,.ws_srv.EmitRequireRenegotiateSessionRequest\x1a-.ws_srv.EmitRequireRenegotiateSessionResponseB\x0eZ\fgrpc/ws_grpcb\x06proto3"

var (
	file_ws_proto_rawDescOnce sync.Once
	file_ws_proto_rawDescData []byte
)

func file_ws_proto_rawDescGZIP() []byte {
	file_ws_proto_rawDescOnce.Do(func() {
		file_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)))
	})
	return file_ws_proto_rawDescData
}

var file_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ws_proto_goTypes = []any{
	(*EmitRoomCreatedRequest)(nil),                // 0: ws_srv.EmitRoomCreatedRequest
	(*EmitRoomCreatedResponse)(nil),               // 1: ws_srv.EmitRoomCreatedResponse
	(*EmitJoinRoomReequest)(nil),                  // 2: ws_srv.EmitJoinRoomReequest
	(*EmitJoinRoomResponse)(nil),                  // 3: ws_srv.EmitJoinRoomResponse
	(*EmitRequireRenegotiateSessionRequest)(nil),  // 4: ws_srv.EmitRequireRenegotiateSessionRequest
	(*EmitRequireRenegotiateSessionResponse)(nil), // 5: ws_srv.EmitRequireRenegotiateSessionResponse
}
var file_ws_proto_depIdxs = []int32{
	0, // 0: ws_srv.WebsocketServices.EmitRoomCreated:input_type -> ws_srv.EmitRoomCreatedRequest
	2, // 1: ws_srv.WebsocketServices.EmitJoinRoom:input_type -> ws_srv.EmitJoinRoomReequest
	4, // 2: ws_srv.WebsocketServices.EmitRequireRenegotiateSession:input_type -> ws_srv.EmitRequireRenegotiateSessionRequest
	1, // 3: ws_srv.WebsocketServices.EmitRoomCreated:output_type -> ws_srv.EmitRoomCreatedResponse
	3, // 4: ws_srv.WebsocketServices.EmitJoinRoom:output_type -> ws_srv.EmitJoinRoomResponse
	5, // 5: ws_srv.WebsocketServices.EmitRequireRenegotiateSession:output_type -> ws_srv.EmitRequireRenegotiateSessionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ws_proto_init() }
func file_ws_proto_init() {
	if File_ws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ws_proto_goTypes,
		DependencyIndexes: file_ws_proto_depIdxs,
		MessageInfos:      file_ws_proto_msgTypes,
	}.Build()
	File_ws_proto = out.File
	file_ws_proto_goTypes = nil
	file_ws_proto_depIdxs = nil
}
